# Generated by Django 2.1.2 on 2018-12-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyersregistry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyersInventoryPage',
            new_name='BuyersDirectoryPage',
        ),
        migrations.RenameField(
            model_name='buyersdirectorypage',
            old_name='buyers_iniventory_page',
            new_name='buyers_directory_page',
        ),
    ]
