# Generated by Django 2.1.2 on 2019-01-13 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=200, null=True)),
                ('listing_id', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('financing_price', models.IntegerField()),
                ('asking_price', models.IntegerField()),
                ('image_main', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_1', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_2', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_3', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_4', models.ImageField(blank=True, upload_to='images/listings/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=200)),
                ('business_type', models.CharField(blank=True, max_length=200, null=True)),
                ('listing_id', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('financing_price', models.IntegerField()),
                ('asking_price', models.IntegerField()),
                ('image_main', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_1', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_2', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_3', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_4', models.ImageField(blank=True, upload_to='images/listings/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('commercial', 'commercial'), ('business', 'business')], default='business', max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(max_length=50)),
                ('served_as', models.CharField(max_length=50)),
                ('completion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/featured_image/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='images/listings/')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.ImageUpload')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
