# Generated by Django 2.1.2 on 2018-12-19 13:15

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=50)),
                ('area_slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=100)),
                ('business_type_slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('commercial', 'commercial'), ('business', 'business')], default='business', max_length=20)),
                ('listing_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('image_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('image_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('image_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('description', ckeditor.fields.RichTextField()),
                ('price', models.IntegerField()),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listing.Area')),
                ('business_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listing.Business_Type')),
                ('disclaimer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtor.Disclaimer')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtor.Realtor')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='listing.Status'),
        ),
    ]
