# Generated by Django 2.1.2 on 2019-01-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commerciallisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
