# Generated by Django 2.1.2 on 2018-12-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20181221_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='listing.Area'),
        ),
    ]
