# Generated by Django 2.1.2 on 2019-01-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20190116_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslisting',
            options={'ordering': ['my_order'], 'verbose_name_plural': 'My ordered objects'},
        ),
        migrations.AlterField(
            model_name='businesslisting',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
