# Generated by Django 2.1.2 on 2018-12-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20181221_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='listing',
            name='financing',
            field=models.IntegerField(null=True),
        ),
    ]
