# Generated by Django 2.1.2 on 2018-12-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20181227_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='financing',
            new_name='finance',
        ),
    ]
