# Generated by Django 2.1.2 on 2019-01-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20190118_0649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesslisting',
            options={'ordering': ['my_order']},
        ),
        migrations.AlterModelOptions(
            name='commerciallisting',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='commerciallisting',
            name='my_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
