# Generated by Django 2.1.2 on 2019-01-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_auto_20181230_1129'),
        ('listing', '0005_auto_20190118_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslisting',
            name='nda_and_disclaimer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtor.Disclaimer'),
        ),
        migrations.AddField(
            model_name='commerciallisting',
            name='nda_and_disclaimer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtor.Disclaimer'),
        ),
    ]
