# Generated by Django 2.1.2 on 2018-12-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_featuredlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
