# Generated by Django 2.1.2 on 2018-12-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20181228_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedDeals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('commercial', 'commercial'), ('business', 'business')], default='business', max_length=20)),
                ('listing_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=500, unique=True)),
                ('subtitle', models.CharField(max_length=50)),
                ('served_as', models.CharField(max_length=50)),
                ('completion', models.DateField()),
            ],
        ),
    ]
