# Generated by Django 2.1.2 on 2019-01-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20190118_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='nda_and_disclaimer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtor.Disclaimer'),
        ),
        migrations.AlterField(
            model_name='commerciallisting',
            name='nda_and_disclaimer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtor.Disclaimer'),
        ),
    ]
