# Generated by Django 2.1.2 on 2018-12-29 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_completeddeals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeddeals',
            name='listing_id',
        ),
        migrations.AddField(
            model_name='completeddeals',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.Area'),
        ),
    ]
