# Generated by Django 2.1.2 on 2018-12-29 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_auto_20181229_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_completed',
        ),
    ]
