# Generated by Django 2.1.2 on 2019-01-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_auto_20181230_1129'),
        ('listing', '0009_businesslisting_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='commerciallisting',
            name='realtor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='realtor.Realtor'),
        ),
    ]
