# Generated by Django 2.1.2 on 2018-12-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_remove_listing_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_main',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
