# Generated by Django 2.1.2 on 2019-01-27 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_commerciallisting_realtor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
        migrations.DeleteModel(
            name='Business_Type',
        ),
    ]
