# Generated by Django 2.1.2 on 2018-12-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_auto_20181230_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/listings/')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='featuredlisting',
            name='image',
            field=models.ImageField(upload_to='images/featured_image/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='images/listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images/listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images/listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='images/listings/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_main',
            field=models.ImageField(upload_to='images/listings/'),
        ),
    ]
