# Generated by Django 2.1.2 on 2019-02-01 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_auto_20190127_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslisting',
            name='realtor',
        ),
        migrations.RemoveField(
            model_name='commerciallisting',
            name='realtor',
        ),
    ]
