# Generated by Django 2.1.2 on 2018-12-30 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_auto_20181230_0506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.ImageUploadText'),
        ),
    ]
