# Generated by Django 2.1.2 on 2018-12-30 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0013_auto_20181230_0617'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='ImageUploadText',
        ),
        migrations.AddField(
            model_name='imageuploadfile',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.ImageUpload'),
        ),
    ]
