# Generated by Django 2.1.2 on 2018-12-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0016_auto_20181230_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='images',
        ),
        migrations.RemoveField(
            model_name='imageuploadfile',
            name='image',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='image',
            field=models.FileField(null=True, upload_to='images/listings/'),
        ),
        migrations.AddField(
            model_name='imageuploadfile',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.ImageUpload'),
        ),
    ]
