# Generated by Django 2.1.2 on 2018-12-30 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_auto_20181230_0632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imageuploadfile',
            name='images',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='imageuploadfile',
            name='image',
            field=models.FileField(null=True, upload_to='images/listings/'),
        ),
        migrations.AlterField(
            model_name='imageuploadfile',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listing.ImageUpload'),
        ),
    ]
