# Generated by Django 2.1.2 on 2018-12-30 11:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0018_auto_20181230_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
