# Generated by Django 2.1.2 on 2019-01-02 04:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0019_auto_20181230_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('Location', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('financing_price', models.IntegerField()),
                ('asking_price', models.IntegerField()),
                ('image_main', models.ImageField(upload_to='images/listings/')),
                ('image_1', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_2', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_3', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_4', models.ImageField(blank=True, upload_to='images/listings/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='area',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='realtor',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
