# Generated by Django 2.1.2 on 2019-01-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0021_auto_20190102_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='image_main',
            field=models.ImageField(blank=True, upload_to='images/listings/'),
        ),
    ]
