# Generated by Django 2.1.2 on 2019-01-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0022_auto_20190102_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslisting',
            name='description',
            field=models.TextField(),
        ),
    ]
