# Generated by Django 2.1.2 on 2019-01-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0023_auto_20190102_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('financing_price', models.IntegerField()),
                ('asking_price', models.IntegerField()),
                ('image_main', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_1', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_2', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_3', models.ImageField(blank=True, upload_to='images/listings/')),
                ('image_4', models.ImageField(blank=True, upload_to='images/listings/')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
