# Generated by Django 2.1.2 on 2019-01-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0024_commerciallisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslisting',
            name='business_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commerciallisting',
            name='business_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
