# Generated by Django 2.1.2 on 2019-01-07 15:55

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('listing', '0025_auto_20190105_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesslisting',
            name='testimagefield',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimage', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
