# Generated by Django 2.1.2 on 2019-01-08 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0027_auto_20190108_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesslisting',
            name='testimagefield',
        ),
    ]
