# Generated by Django 2.1.2 on 2019-01-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0028_remove_businesslisting_testimagefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completeddeals',
            name='slug',
        ),
        migrations.AlterField(
            model_name='completeddeals',
            name='area',
            field=models.CharField(max_length=100),
        ),
    ]
