# Generated by Django 2.1.2 on 2019-01-25 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='listing_title',
            new_name='business',
        ),
    ]
