# Generated by Django 2.1.2 on 2019-01-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feedpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='date',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='published',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
