# Generated by Django 2.1.2 on 2018-12-19 13:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', ckeditor.fields.RichTextField()),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homepage_heading', models.CharField(blank=True, default='Buy Or Sell Your Business', max_length=150)),
                ('homepage_subheading', ckeditor.fields.RichTextField(blank=True, default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam pretium elit id ligula mollis commodo. Fusce at quam turpis. Cras ornare bibendum dui, nec rutrum neque maximus non. Integer aliquam tempus quam in vulputate. Suspendisse ultrices eu tellus ac accumsan.')),
                ('sellerbox_subtitle', ckeditor.fields.RichTextField(blank=True, default='Discover how much property sold for with our comprehensive house price data.')),
                ('buyerbox_subtitle', ckeditor.fields.RichTextField(blank=True, default='Ensure you find the right home, near the right school with new School Checker tool.')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
