# Generated by Django 2.1.2 on 2018-12-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buying',
            new_name='BuyingProcess',
        ),
    ]
