# Generated by Django 2.1.2 on 2018-12-29 07:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_auto_20181220_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sociallink',
            old_name='instagram',
            new_name='youtube',
        ),
        migrations.AddField(
            model_name='home',
            name='buyerbox_title',
            field=ckeditor.fields.RichTextField(blank=True, default="I'm a Buyer"),
        ),
        migrations.AddField(
            model_name='home',
            name='sellerbox_title',
            field=ckeditor.fields.RichTextField(blank=True, default="I'm a Seller"),
        ),
    ]
