# Generated by Django 2.1.2 on 2018-12-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_auto_20181229_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='buyerbox_button',
            field=models.CharField(default='Buying Transaction ', max_length=30),
        ),
        migrations.AddField(
            model_name='home',
            name='sellerbox_button',
            field=models.CharField(default='Selling Transaction ', max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='buyerbox_title',
            field=models.CharField(blank=True, default="I'm a Buyer", max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='sellerbox_title',
            field=models.CharField(blank=True, default="I'm a Seller", max_length=30),
        ),
    ]
