# Generated by Django 2.1.2 on 2018-12-29 09:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0006_auto_20181229_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='homepage_heading',
        ),
        migrations.RemoveField(
            model_name='home',
            name='homepage_subheading',
        ),
        migrations.AddField(
            model_name='home',
            name='homepage',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='here some heading will go..'),
        ),
        migrations.AlterField(
            model_name='about',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
