# Generated by Django 2.1.2 on 2019-01-05 06:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_auto_20181230_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellYourBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
