# Generated by Django 2.1.2 on 2019-01-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_sellyourbusiness'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer_image_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
