# Generated by Django 2.1.2 on 2019-01-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_footer_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer_image_link',
            name='image',
            field=models.ImageField(null=True, upload_to='images/footer_images'),
        ),
    ]
