# Generated by Django 2.1.2 on 2019-01-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_footer_image_link_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='footer_image_link',
            new_name='footer_image',
        ),
    ]
