# Generated by Django 2.1.2 on 2019-01-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_auto_20190115_0519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='footer_image',
            new_name='FooterImages',
        ),
    ]
