# Generated by Django 2.1.2 on 2019-01-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_auto_20190115_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('home', 'home'), ('about', 'about'), ('business', 'business'), ('buying-process', 'buying-process'), ('small-business-finance', 'small-business-finance'), ('business-listing', 'business-listing'), ('commercial-listing', 'commercial-listing'), ('blog', 'blog'), ('download', 'download'), ('selling-process', 'selling-process'), ('completed-deals', 'completed-deals'), ('sell-your-business', 'sell-your-business'), ('buyers-directory', 'buyers-directory'), ('buyers-directory-register', 'buyers-directory-register'), ('endorsements', 'endorsements'), ('news', 'news'), ('contact', 'contact')], default='home', max_length=50)),
                ('meta_title', models.TextField()),
                ('meta_description', models.TextField()),
                ('meta_keywords', models.TextField()),
            ],
        ),
    ]
