# Generated by Django 2.1.2 on 2019-01-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_metatags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatags',
            name='page_name',
            field=models.CharField(choices=[('home', 'home'), ('our-team', 'our-team'), ('about-business', 'about-business'), ('business', 'business'), ('buying-process', 'buying-process'), ('small-business-finance', 'small-business-finance'), ('business-listing', 'business-listing'), ('commercial-listing', 'commercial-listing'), ('blog', 'blog'), ('download', 'download'), ('selling-process', 'selling-process'), ('completed-deals', 'completed-deals'), ('sell-your-business', 'sell-your-business'), ('buyers-directory', 'buyers-directory'), ('buyers-directory-register', 'buyers-directory-register'), ('endorsements', 'endorsements'), ('news', 'news'), ('contact', 'contact')], default='home', max_length=50),
        ),
    ]
