# Generated by Django 2.1.2 on 2019-01-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0017_auto_20190127_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metatags',
            old_name='meta_keywords',
            new_name='meta_keyword',
        ),
    ]
